### ISSUE TITLE
pluggable authentication

### ISSUE THREAD

**Issue by MrLesh** [internetitem/logback-elasticsearch-appender#19]
Hi,
I have a play project and I want to use this library to publish events to Amazon elasticsearch.
Added the reference to it to mt build.sbt as: "com.internetitem" % "logback-elasticsearch-appender" % "1.4"
I tried to add a new authentication class in my project, say the full name is:   utils.AWSUtils.AmazonElasticSearchAuthentication,
I then put this in the appender configuration as:
<authentication class="utils.AWSUtils.AmazonElasticSearchAuthentication"/>

when running the server I receive the following exception:
ERROR in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Could not create component [authentication] of type [utils.AWSUtils.AmazonElasticSearchAuthentication] java.lang.ClassNotFoundException: utils.AWSUtils.AmazonElasticSearchAuthentication
	at java.lang.ClassNotFoundException: utils.AWSUtils.AmazonElasticSearchAuthentication
	at 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at 	at ch.qos.logback.core.util.Loader.loadClass(Loader.java:125)
	at 	at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.begin(NestedComplexPropertyIA.java:100)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:275)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:147)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:129)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at play.api.Logger$.configure(Logger.scala:278)
	at 	at play.api.Logger$.configure(Logger.scala:232)
	at 	at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:73)
	at 	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)
	at 	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)
	at 	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at 	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:153)
	at 	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:150)
	at 	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at 	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:150)
	at 	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121)
	at 	at scala.Option.map(Option.scala:146)
	at 	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121)
	at 	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119)
	at 	at scala.util.Success.flatMap(Try.scala:231)
	at 	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119)
	at 	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111)
	at 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

any thoughts?
Thanks

**Comment by abatkin** [comment]
Sounds like maybe a classloader issue? I'm not sure where your ligback JARs live in your classpath, versus where your utils.AWSUtils... classes live.

**Comment by MrLesh** [comment]
Apparently play has a[ problem with loading a custom logback appender](http://stackoverflow.com/questions/20210574/play-fails-to-load-custom-log-back-appender) so maybe this is the problem.

**Comment by JeffAtDeere** [comment]
This works for me but then my appender is in a separate jar
